import BackboneRouterTest from './backbone/SCTypesFrontEndCoreBackboneRouterTest';
import SCTypesFrontEndCoreBackboneViewTest from './backbone/SCTypesFrontEndCoreBackboneViewTest';
import SCTypesFrontEndCoreApplicationTest from './application/SCTypesFrontEndCoreApplicationTest';
import SCTypesFrontEndCoreBackboneViewTest2 from './backbone/SCTypesFrontEndCoreBackboneViewTest2';
import SCTypesFrontEndCoreDeferredTest from './application/SCTypesFrontEndCoreDeferredTest';

export default [SCTypesFrontEndCoreBackboneViewTest, BackboneRouterTest, SCTypesFrontEndCoreApplicationTest, SCTypesFrontEndCoreBackboneViewTest2, SCTypesFrontEndCoreDeferredTest]